### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kkew3** [noearc/jieba.nvim#5]
同学你好！

非常高兴你对 [jieba.vim](https://github.com/kkew3/jieba.vim) 感兴趣。

可否把 typo "vim.jieba" 改为 "jieba.vim"：

https://github.com/neo451/jieba.nvim/blob/d22a7de7ef553c7640535d2411d8d0c88304b592/README.md?plain=1#L3

---

另：

> **Q**: What should I do when I quote a snippet licensed under MIT from others?

> **GPT**: When quoting a snippet licensed under the MIT License, follow these guidelines:
>
> 1. Attribution: Always credit the original author. This can be done by including a comment in your code or in accompanying documentation.
> 2. Include the License: The MIT License is permissive, but you should include the full text of the license with your code. This is often done in a LICENSE file or as a comment in your source file.
> 3. Be Clear: Make it clear which parts of your code are original and which parts are quoted. This can help prevent confusion about ownership and licensing.
> 4. Respect Modification Rights: If you modify the snippet, you can still use it under the MIT License, but it's good practice to note what changes you've made.
> 5. Documentation: If applicable, document how the snippet fits into your project, especially if it serves a significant purpose.
>
> Example Attribution Comment
>
> ```
> // This code snippet is taken from [Author/Source] and is licensed under the MIT License.
> // Original License Text:
> // MIT License
> // [Insert full license text here]
> ```
>
> By following these steps, you respect the original creator's work while complying with the terms of the MIT License.

非常感谢！

**Comment by neo451** [comment]
好的！感谢提醒

**Comment by neo451** [comment]
已经更改readme和你提到的license问题，请你看一下

**Comment by kkew3** [comment]
👌 非常感谢！
