### ISSUE TITLE
新lazy.nvim 有改动，自动调用 setup 函数

### ISSUE THREAD

**Issue by cxwx** [noearc/jieba.nvim#6]
  Error  07:15:57 notify.error lazy.nvim Failed to run `config` for jieba.nvim

...xu/software/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:383: attempt to call field 'setup' (a nil value)

**Comment by neo451** [comment]
按道理讲 lazy 不会一定调用 setup ？ 我试了一下不会，但是我还是新加了一个 setup，应该已经解决了

**Comment by cxwx** [comment]
解决了，感谢
